name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonarqube:
    name: Analyze Joget modules with SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and Analyze wflow-core
        working-directory: wflow-core
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean install -DskipTests
          mvn sonar:sonar \
            -Dsonar.projectKey=joget-wevioo-wflow-core \
            -Dsonar.host.url=http://192.168.193.128:9000 \
            -Dsonar.login=$SONAR_TOKEN

